name: Release-Tag
on:
  push:
    branches: [ master ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: "v0.0.${{ github.run_number }}"
    